### ISSUE TITLE
`makefileDecent`

### ISSUE THREAD

**Issue by Sklpcc** [pebeto/pebeto.github.io#2]
Hola @pebeto, acabo de encontrar de casualidad tu post acerca de los makefiles :+1: 

Buen trabajo aportando conocimiento para quieres lo necesitan, y en español.

He aqui algo de critica que espero ayude a mejorar futuras publicaciones.

> cada parte del código es compilada manualmente, y eso pues crea complicaciones, tardanzas y/o errores póstumos

Podrias especificar algunos casos? El problema es presentado, pero no hay detalles ni ejemplos. Personalmente he trabajado con `C/C++` durante varios años y rara vez tuve problema con compilaciones. En gran parte porque los editores de texto/IDEs hacian esa parte por mi. El problema que presentas ocurre en esos casos, o solo es si trabajas en entornos mas basicos?

> Uno de los problemas más grandes de enseñanza en mi universidad fue que no nos explicaron cómo es que funcionaba correctamente cada herramienta

No justifico, ya entiendo perfectamente esta parte, pero tambien comprendo que la carrera era ingenieria de sistemas, no ingeniera de software o una carrera tecnica de programacion donde esto si seria imperdonable. my 2¢. :thinking: 

> Un Makefile es un archivo que automatiza la compilación

`Makefile` _per se_ no automatiza la compilacion, sino, indica a `make` como **construir** el programa

> CC = g++
SRCS = src/main.cpp src/Ella.cpp
IDIR = include
OUT = bin/ellanotequiere
ellanotequiere: $(SRCS)
	$(CC) -o $(OUT) $(SRCS) -I $(IDIR)

Entiendo el punto que tratas de demostrar, pero usar tantas variables para los ejemplos siguientes me parece demasiado. Usar nombres demasiados cortos tampoco representa un beneficio, menos en ejemplos. e.g. reescribo lo anterior:

```make
COMPILER=g++
SOURCES=src/main.cpp src/ella.cpp
INCLUDE_DIR=include
OUT_DIR=bin/ellanotequiere

ellanotequiere: $(SOURCES)
    $(COMPILER) -o $(OUTPUT_DIR) $(SOURCES) -I $(INCLUDE_DIR)
```
IMHO al enseñar es mejor ser verboso que pecar de abreviar demasiado (por mas que sean convenciones o "lo que se usa normalmente")

> src/Ella.cpp src/main.cpp

Me parece que mantener la misma convencion en los ejemplos hace que se lea mejor

`src/ella.cpp src/main.cpp`

> OUT = ellanotequiere
ellanotequiere: $(OBJS)

En varios ejemplos he visto que si bien `ellanotequiere` esta definido dentro de una variable, se escribe de nuevo como uno de los targets. Es intencional?

-------------------

> ellanotequiere

Personalmente he econtrado ese nombre un poco distrayente :thinking: pero ya es una opinion subjetiva.

----------------------------------

Seria bueno que agregues referencias y/o links para lectura posterior, alternativas, etc. Por si el lector esta interesado, tenga donde continuar.

Por ejemplo como referencia puedes incluir:
https://www.gnu.org/software/make/
https://www.gnu.org/software/make/manual/html_node/Quick-Reference.html

Y como alternativas para investigar:
[CMAKE](https://cmake.org)

---------------

Si no hay tildes es porque no las tengo en este layout :sweat_smile:

**Comment by pebeto** [comment]
> Podrias especificar algunos casos? 

Hacer referencia a la empresa en donde estuve haciendo prácticas me parece negativo, pero bueno... ya lo dije. En aquella desarrollaba un sistema para la misma usando Delphi para la GUI y C++ para manipular los datos y cálculos. Lo que sucedía es que cuando llegué, ellos compilaban todos aquellos "módulos" y también, si se requería, combinaban cada uno de manera manual (los cuales eran demasiados).
En la estructura del proyecto ya había un Makefile, pero nadie supo cómo usarlo hasta ese entonces. Lo primero que hice fue hacer eso: cambiarlo y enseñarles su poder. Al final, utilizando un simple `make` se ahorraron mucho tiempo.

> El problema que presentas ocurre en esos casos, o solo es si trabajas en entornos mas basicos?

Normalmente este tipo de casos ocurren cuando estás programando en entornos que no son un IDE completamente, como VSCode, VIM, Emacs, Atom, Kakoune, etc. Sin embargo, también pasan en IDES si los proyectos llegan a ser de gran escala.

> Makefile per se no automatiza la compilacion

**my bad**

> Entiendo el punto que tratas de demostrar, pero usar tantas variables para los ejemplos siguientes me parece demasiado.

Imagina un Makefile con infinitas líneas, en donde se haga referencia a un directorio muy largo. Repetir `n` veces su nombre haría a dicho archivo poco mantenible, y para eso es que se guardan en variables. Es cierto que los directorios tienen nombres cortos en el ejemplo, pero...

> Usar nombres demasiados cortos tampoco representa un beneficio

... mi idea de utilizar un ejemplo como ese era el de utilizar los nombres de variable que normalmente utilizan los proyectos de C++. Además, todo eso lo hice intencionalmente para obligar al lector a leer desde un inicio, porque el ejemplo se desarrolla desde la forma más básica.

> En varios ejemplos he visto que si bien ellanotequiere esta definido dentro de una variable, se escribe de nuevo como uno de los targets. Es intencional?

Sí, es intencional. En la mayoría de Makefiles encontrarás que la última regla a cumplir lleva un nombre estático, mas no la variable que tuviese su valor.

> Seria bueno que agregues referencias y/o links para lectura posterior, alternativas, etc. Por si el lector esta interesado, tenga donde continuar.

Gracias, había olvidado ese punto. Ahora mismo corregiré algunas cosas y añadiré de dónde investigué.
